const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Text.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.MoveAtAngle,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{direcao: 0},
	{"8Direções": 0},
	{Protagonista: 0},
	{CentrarEm: 0},
	{Mira: 0},
	{Mouse: 0},
	{Fixar: 0},
	{Camera: 0},
	{Teclado: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Sprite3: 0},
	{Mosaico2: 0},
	{Sprite9: 0},
	{inimigo: 0},
	{Sprite10: 0},
	{tentarnovamente: 0},
	{menu: 0},
	{Navegador: 0},
	{Sprite13: 0},
	{Inimigo2: 0},
	{inimigo3: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{começo: 0},
	{trancado: 0},
	{bau: 0},
	{animacao: 0},
	{Sprite: 0},
	{fechado: 0},
	{boss: 0},
	{falaBOSS: 0},
	{questão1: 0},
	{Sprite2: 0},
	{falafinal: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{EntradaDeTexto: 0},
	{enter: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Texto4: 0},
	{pergunta1: 0},
	{score: 0},
	{tempo: 0},
	{Texto5: 0},
	{Texto6: 0},
	{Texto7: 0},
	{Texto8: 0},
	{pergunta2: 0},
	{pergunta3: 0},
	{Texto9: 0},
	{Texto10: 0},
	{Texto11: 0},
	{Texto12: 0},
	{Texto13: 0},
	{Texto14: 0},
	{Texto15: 0},
	{Texto16: 0},
	{pergunta4: 0},
	{animação2: 0},
	{Áudio: 0},
	{Sprite7: 0}
];

self.InstanceType = {
	Protagonista: class extends self.ISpriteInstance {},
	Mira: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	tentarnovamente: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	inimigo3: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	começo: class extends self.ISpriteInstance {},
	trancado: class extends self.ISpriteInstance {},
	bau: class extends self.ISpriteInstance {},
	animacao: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	fechado: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	falaBOSS: class extends self.ISpriteInstance {},
	questão1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	falafinal: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	EntradaDeTexto: class extends self.ITextInputInstance {},
	enter: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	pergunta1: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	tempo: class extends self.ISpriteInstance {},
	Texto5: class extends self.ITextInstance {},
	Texto6: class extends self.ITextInstance {},
	Texto7: class extends self.ITextInstance {},
	Texto8: class extends self.ITextInstance {},
	pergunta2: class extends self.ISpriteInstance {},
	pergunta3: class extends self.ISpriteInstance {},
	Texto9: class extends self.ITextInstance {},
	Texto10: class extends self.ITextInstance {},
	Texto11: class extends self.ITextInstance {},
	Texto12: class extends self.ITextInstance {},
	Texto13: class extends self.ITextInstance {},
	Texto14: class extends self.ITextInstance {},
	Texto15: class extends self.ITextInstance {},
	Texto16: class extends self.ITextInstance {},
	pergunta4: class extends self.ISpriteInstance {},
	animação2: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}